TEXFILE = report
PRESENTATION = presentation
PDFLATEX = pdflatex
GREEKPDFLATEX = report_translated_greek
BIBTEX = bibtex

all: $(TEXFILE).pdf $(PRESENTATION).pdf $(GREEKPDFLATEX).pdf

$(TEXFILE).pdf: $(TEXFILE).tex $(TEXFILE).bib
	$(PDFLATEX) $(TEXFILE)
	$(BIBTEX) $(TEXFILE)
	$(PDFLATEX) $(TEXFILE)
	$(PDFLATEX) $(TEXFILE)

$(PRESENTATION).pdf: $(PRESENTATION).tex $(PRESENTATION).bib
	$(PDFLATEX) $(PRESENTATION)
	$(BIBTEX) $(PRESENTATION)
	$(PDFLATEX) $(PRESENTATION)
	$(PDFLATEX) $(PRESENTATION)

$(GREEKPDFLATEX).pdf: $(GREEKPDFLATEX).tex $(GREEKPDFLATEX).bib
	$(PDFLATEX) $(GREEKPDFLATEX)
	$(BIBTEX) $(GREEKPDFLATEX)
	$(PDFLATEX) $(GREEKPDFLATEX)
	$(PDFLATEX) $(GREEKPDFLATEX)

clean:
	rm -f $(TEXFILE).aux $(TEXFILE).bbl $(TEXFILE).blg $(TEXFILE).log $(TEXFILE).out $(TEXFILE).toc $(PRESENTATION).aux $(PRESENTATION).log $(PRESENTATION).nav $(PRESENTATION).out $(PRESENTATION).snm $(PRESENTATION).toc $(PRESENTATION).bbl $(PRESENTATION).blg $(GREEKPDFLATEX).aux $(GREEKPDFLATEX).log $(GREEKPDFLATEX).out $(GREEKPDFLATEX).bbl $(GREEKPDFLATEX).blg

distclean: clean
	rm -f $(TEXFILE).pdf $(PRESENTATION).pdf $(GREEKPDFLATEX).pdf
